[env:m5dial_usb]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
  m5stack/M5Unified@0.1.14
  m5stack/M5Dial@1.0.2
  knolleary/PubSubClient@2.8
  bblanchon/ArduinoJson

upload_port = /dev/ttyACM0   ; change if your serial port is different


[env:m5dial_ota]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
  m5stack/M5Unified@0.1.14
  m5stack/M5Dial@1.0.2
  knolleary/PubSubClient@2.8
  bblanchon/ArduinoJson

upload_protocol = espota
upload_port = 192.168.1.37  ; <<< replace with your M5Dial’s IP or hostname (M5Dial.local)
upload_flags =
  --auth=Fanfo1122
